-- Durable try-on job state for polling across serverless instances/restarts.
-- Job ids are generated by the app and are stored as text for compatibility
-- with existing local/dev fallback ids.

create table if not exists public.try_on_jobs (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  input jsonb not null,
  status text not null check (status in ('queued', 'processing', 'completed', 'failed')),
  progress int not null default 0 check (progress >= 0 and progress <= 100),
  stage text not null check (stage in ('upload', 'validation', 'processing', 'generating', 'final')),
  status_message text not null default '',
  image_url text,
  error_code text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists try_on_jobs_user_updated_idx
  on public.try_on_jobs (user_id, updated_at desc);

alter table public.try_on_jobs enable row level security;

drop policy if exists "try_on_jobs_select_own" on public.try_on_jobs;
create policy "try_on_jobs_select_own" on public.try_on_jobs
  for select using (auth.uid() = user_id);

-- App server/service-role code owns writes. Clients read through API routes.
revoke insert, update, delete on table public.try_on_jobs from anon, authenticated;
grant select on table public.try_on_jobs to authenticated;
